# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 22:39
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bookRev', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authors',
            managers=[
                ('authorMgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='books',
            managers=[
                ('bookMgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reviews',
            managers=[
                ('reviewMgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
